# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

addons:
  postgresql: "9.4"

install: pip install -r requirements.txt

before_script:
  - psql -c 'create database {{ cookiecutter.app_name }}_test;' -U postgres

script: "nosetests --with-coverage --cover-package={{ cookiecutter.app_name }}"

after_success:
  coveralls